name: clase_02

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_job:
    # if: false para forzar a no ejecutarse
    if: ${{ github.ref == 'refs/heads/main'}} # contextos | siempre y cuando la referencia sea main
    needs: first_job
    runs-on: ubuntu-latest # debe ser el mismo que el primero
    
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ github.ref }}"
