name: clase_03

on: push

jobs:
  first_job:  
    runs-on: ubuntu-latest  

    steps:

      - name: Print variable
        run: echo "${{ secrets.TOKEN_SECRET }}" 

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Instalar dependencias
        run: npm install

      - name: Run test 
        run: npx jest  # ¡Cambio clave aquí!
