name: Publicar paquete en GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publicar-paquete:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@calvarezlock'  # ¡En minúsculas!

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar configuración
        run: |
          echo "Registry config:"
          npm config get registry
          echo "Scope config:"
          npm config get scope
          echo "Package name:"
          npm pkg get name

      - name: Publicar paquete
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}